/*  Vector field function and events for Radau integrator.
  This code was automatically generated by PyDSTool, but may be modified by hand. */

#include <math.h>
#include <Python.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "events.h"
#include "maxmin.h"
#include "signum.h"
#include "vfield.h"

extern double *gICs;
extern double **gBds;
extern double globalt0;

static double pi = 3.1415926535897931;

double signum(double x)
{
  if (x<0) {
    return -1;
  }
  else if (x==0) {
    return 0;
  }
  else if (x>0) {
    return 1;
  }
  else {
    /* must be that x is Not-a-Number */
    return x;
  }
}


/* Variable, aux variable, parameter, and input definitions: */ 
#define Kin0	p_[0]
#define LQDA2_0	p_[1]
#define Mass0	p_[2]
#define P0c	p_[3]
#define kappaQDA2_0	p_[4]
#define offset	p_[5]
#define H	Y_[0]
#define Ss	Y_[1]
#define Sx	Y_[2]
#define Sy	Y_[3]
#define dK	Y_[4]
#define px	Y_[5]
#define py	Y_[6]
#define s	Y_[7]
#define start	Y_[8]
#define ts	Y_[9]
#define x	Y_[10]
#define y	Y_[11]

double NaN_event(unsigned n_, double t, double *Y_, double *p_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_);
double passto1(unsigned n_, double t, double *Y_, double *p_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_);

double KinEn(double __dK__, double *p_, double *wk_, double *xv_);
double Lbeta(double __dK__, double *p_, double *wk_, double *xv_);
double Lgamma(double __dK__, double *p_, double *wk_, double *xv_);
double Pc(double __dK__, double *p_, double *wk_, double *xv_);
double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_);
double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_);
double globalindepvar(double t, double *p_, double *wk_, double *xv_);
double hs(double __x__, double *p_, double *wk_, double *xv_);
double initcond(char *varname, double *p_, double *wk_, double *xv_);
int getindex(char *name, double *p_, double *wk_, double *xv_);
int heav(double x_, double *p_, double *wk_, double *xv_);

int N_EVENTS = 2;
void assignEvents(EvFunType *events){
 events[0] = &NaN_event;
events[1] = &passto1;

}

void auxvars(unsigned, unsigned, double, double*, double*, double*, unsigned, double*, unsigned, double*);
void jacobian(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
void jacobianParam(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
int N_AUXVARS = 0;


int N_EXTINPUTS = 0;


void vfieldfunc(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){
/* Verbose code insert -- begin */
state = [x,y,ts,px,py,dK,Sx,Sy,Ss,H]
    xp,yp,tp,pxp,pyp,dKp,Sxp,Syp,Ssp,Hp = ds.Particle.RHS(state, ds.Element)
/* Verbose code insert -- end */


f_[0] = Hp;
f_[1] = Ssp;
f_[2] = Sxp;
f_[3] = Syp;
f_[4] = dKp;
f_[5] = pxp;
f_[6] = pyp;
f_[7] = 1;
f_[8] = 0;
f_[9] = tp;
f_[10] = xp;
f_[11] = yp;

}




double KinEn(double __dK__, double *p_, double *wk_, double *xv_) {


return Kin0*(1+__dK__);

}


double Lbeta(double __dK__, double *p_, double *wk_, double *xv_) {


return sqrt(pow(Lgamma(__dK__, p_, wk_, xv_),2)-1)/Lgamma(__dK__, p_, wk_, xv_);

}


double Lgamma(double __dK__, double *p_, double *wk_, double *xv_) {


return KinEn(__dK__, p_, wk_, xv_)/Mass0+1 ;

}


double Pc(double __dK__, double *p_, double *wk_, double *xv_) {


return sqrt(pow(Mass0+KinEn(__dK__, p_, wk_, xv_),2)-pow(Mass0,2));

}


double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ > e2_) {return e1_;} else {return e2_;};
}


double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {return e3_;} else {return temp_;};
}


double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {temp_ = e3_;};
if (e4_ > temp_) {return e4_;} else {return temp_;};
}


double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ < e2_) {return e1_;} else {return e2_;};
}


double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {return e3_;} else {return temp_;};
}


double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {temp_ = e3_;};
if (e4_ < temp_) {return e4_;} else {return temp_;};
}


double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_) {
  if (cond_) {return e1_;} else {return e2_;};
}


double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_) {
  return gBds[which_bd][getindex(name, p_, wk_, xv_)];
}


double globalindepvar(double t, double *p_, double *wk_, double *xv_) {
  return globalt0+t;
}


double hs(double __x__, double *p_, double *wk_, double *xv_) {


return 1+__x__*kappaQDA2_0 ;

}


double initcond(char *varname, double *p_, double *wk_, double *xv_) {

  if (strcmp(varname, "H")==0)
	return gICs[0];
  else if (strcmp(varname, "Ss")==0)
	return gICs[1];
  else if (strcmp(varname, "Sx")==0)
	return gICs[2];
  else if (strcmp(varname, "Sy")==0)
	return gICs[3];
  else if (strcmp(varname, "dK")==0)
	return gICs[4];
  else if (strcmp(varname, "px")==0)
	return gICs[5];
  else if (strcmp(varname, "py")==0)
	return gICs[6];
  else if (strcmp(varname, "s")==0)
	return gICs[7];
  else if (strcmp(varname, "start")==0)
	return gICs[8];
  else if (strcmp(varname, "ts")==0)
	return gICs[9];
  else if (strcmp(varname, "x")==0)
	return gICs[10];
  else if (strcmp(varname, "y")==0)
	return gICs[11];
  else {
	fprintf(stderr, "Invalid variable name %s for initcond call\n", varname);
	return 0.0/0.0;
	}
}


int getindex(char *name, double *p_, double *wk_, double *xv_) {

  if (strcmp(name, "H")==0)
	return 0;
  else if (strcmp(name, "Ss")==0)
	return 1;
  else if (strcmp(name, "Sx")==0)
	return 2;
  else if (strcmp(name, "Sy")==0)
	return 3;
  else if (strcmp(name, "dK")==0)
	return 4;
  else if (strcmp(name, "px")==0)
	return 5;
  else if (strcmp(name, "py")==0)
	return 6;
  else if (strcmp(name, "s")==0)
	return 7;
  else if (strcmp(name, "start")==0)
	return 8;
  else if (strcmp(name, "ts")==0)
	return 9;
  else if (strcmp(name, "x")==0)
	return 10;
  else if (strcmp(name, "y")==0)
	return 11;
  else if (strcmp(name, "Kin0")==0)
	return 12;
  else if (strcmp(name, "LQDA2_0")==0)
	return 13;
  else if (strcmp(name, "Mass0")==0)
	return 14;
  else if (strcmp(name, "P0c")==0)
	return 15;
  else if (strcmp(name, "kappaQDA2_0")==0)
	return 16;
  else if (strcmp(name, "offset")==0)
	return 17;
  else {
	fprintf(stderr, "Invalid name %s for getindex call\n", name);
	return 0.0/0.0;
	}
}


int heav(double x_, double *p_, double *wk_, double *xv_) {
  if (x_>0.0) {return 1;} else {return 0;}
}

void auxvars(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){


}

double NaN_event(unsigned n_, double t, double *Y_, double *p_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
return  pow(Pc(dK, p_, wk_, xv_),2)-pow(P0c,2)*(pow(px,2)+pow(py,2))-offset; 
}

double passto1(unsigned n_, double t, double *Y_, double *p_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
return  s-LQDA2_0; 
}


void massMatrix(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobian(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobianParam(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}
